spring:
  application:
    name: WMSapi
  cloud:
    gateway:
      routes:
        - id: event-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/event/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: eventCircuitBreaker
                fallbackUri: forward:/fallback/event
        - id: guest-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/guest/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: eventCircuitBreaker
                fallbackUri: forward:/fallback/guest
        - id: table-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/table/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: tableCircuitBreaker
                fallbackUri: forward:/fallback/table
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
    cache:
      type: redis
      ttl-seconds: 120
