server:
  port: 8082
spring:
  application:
    name: guestService
  datasource:
    url: jdbc:postgresql://localhost:5432/guest_db
    username: postgres
    password: "orkhan2025"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
    cache:
      type: redis
      ttl-seconds: 120
  mail:
    host: smtp.gmail.com
    port: 587
    username: ordukhanm20@gmail.com
    password: vyiywrchnhdotmwr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000
#      refresh-token:
#        expiration: 604800000
logging:
  file:
    name: guest-service.log
  level:
    com:
      ltc:
        guestservice: INFO
    org:
      springframework:
        web: DEBUG
        data.redis: DEBUG

